version: '3.8'


services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - env/.env.prod
    depends_on:
      - db
  bot:
    image: bot
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: python manage.py bot
    ports:
      - 8443:8443
    env_file:
      - env/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
      - POSTGRES_DB=db_for_django_cache_test
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume: